<?php
define("_A", "at");
define("_ACTU", "News");
define("_ACTU_AUTEUR", "Published by");
define("_ACTU_DATE", "the");
define("_ACTU_COMMENTAIRES", "Comments");
define("_ADMIN_VIEU_NK", "INFORMATION");
define("_ADMIN_VIEU_NK_ACCUEIL", "Administration home");
define("_ARCHIVES", "Archives");
define("_ARTICLES", "Articles");
define("_ARTICLES_DERNIERS", "Last articles");
define("_ARTICLES_DATE", "Published on");
define("_ARTICLES_AUTEUR", "by");
define("_CALENDRIER", "Calendar");
define("_COMMUNAUTE", "Community");
define("_DEFI", "Defy us !");
define("_EQUIPE", "Team members");
define("_EQUIPE_TITRE", "Team");
define("_FOOTER_NK", " Powered by ");
define("_FOOTER_NK_TITLE", "Official Nuked-klan website");
define("_FOOTER_ROYAL", "Template by ");
define("_FOOTER_ROYAL_TITLE", "Download Nuked-klan templates");
define("_FORUM", "Forum");
define("_FORUM_DERNIERS", "Chat");
define("_FORUM_REPONSES", "answer(s)");
define("_FORUM_SUJET_DISCUSSION", "Created by ");
define("_FORUM_SUJET_REPONSE", "Answer by ");
define("_GALERIE", "Gallery");
define("_INFO", "Information");
define("_LE", "on");
define("_LIENS", "Links");
define("_LIRE", "Read");
define("_LIVREDOR", "Guestbook");
define("_EN_LIGNE_BLOCK", "Who is online ?");
define("_MEMBRES", "Members");
define("_MP_VOUS", "You got ");
define("_MP_NONLU", " new message");
define("_MP_NONLUS", " new messages");
define("_MP_AUCUN", "0 new message");
define("_PHOTOS_DERNIERES", "Last photos");
define("_RECHERCHER", "Search");
define("_RECRUTEMENT", "Recruit");
define("_RSS_ACTU", "20 last news");
define("_RSS_ARTICLES", "20 last articles");
define("_RSS_TELECHARGEMENTS", "20 last downloads");
define("_RSS_LIENS", "20 last links");
define("_RSS_GALERIE", "20 last images");
define("_RSS_FORUM", "20 last threads");
define("_STATS", "Stats");
define("_SUGGESTIONS", "Suggest");
define("_TELECHARGEMENTS", "Download");
define("_USER_CONNEXION", "Log on");
define("_USER_CONNEXION_TITRE", "Log on to your account");
define("_USER_DECONNEXION", "Log out");
define("_USER_DECONNEXION_TITRE", "Log out from website");
define("_USER_ENREGISTREMENT", "Create account");
define("_USER_ENREGISTREMENT_TITRE", "Create your account now");
define("_USER_COMPTE_TITLE", "My account");
define("_USER_ADMIN", "Admin");
define("_USER_ADMIN_TITLE", "Administration");
define("_USER_PASSPERDU", "?");
define("_USER_PASSPERDU_TITRE", "Forgot your password ?");
define("_USER_OK", "OK");
define("_VIDEO_MOMENT", "Recent video");
?>