<?php
define("_A", "à");
define("_ACTU", "Actualités");
define("_ACTU_AUTEUR", "Publié par");
define("_ACTU_DATE", "le");
define("_ACTU_COMMENTAIRES", "Commentaires");
define("_ADMIN_VIEU_NK", "INFORMATION");
define("_ADMIN_VIEU_NK_ACCUEIL", "Accueil administration");
define("_ARCHIVES", "Archives");
define("_ARTICLES", "Articles");
define("_ARTICLES_DERNIERS", "Derniers articles");
define("_ARTICLES_DATE", "Publié le");
define("_ARTICLES_AUTEUR", "par");
define("_CALENDRIER", "Calendrier");
define("_COMMUNAUTE", "Communauté");
define("_DEFI", "Nous défier !");
define("_EQUIPE", "Membres de l'équipe");
define("_EQUIPE_TITRE", "Equipe");
define("_FOOTER_NK", " Propulsé par ");
define("_FOOTER_NK_TITLE", "Site officiel du CMS Nuked-klan");
define("_FOOTER_ROYAL", "Thème par ");
define("_FOOTER_ROYAL_TITLE", "Production de thèmes Nuked-klan");
define("_FORUM", "Forum");
define("_FORUM_DERNIERS", "Discussions");
define("_FORUM_REPONSES", "réponse(s)");
define("_FORUM_SUJET_DISCUSSION", "Créée par ");
define("_FORUM_SUJET_REPONSE", "Réponse de ");
define("_GALERIE", "Galerie");
define("_INFO", "Information");
define("_LE", "le");
define("_LIENS", "Liens Web");
define("_LIRE", "Lire");
define("_LIVREDOR", "Livre d'or");
define("_EN_LIGNE_BLOCK", "Qui est en ligne ?");
define("_MEMBRES", "Membres");
define("_MP_VOUS", "Vous avez ");
define("_MP_NONLU", " message non lu");
define("_MP_NONLUS", " messages non lus");
define("_MP_AUCUN", "Aucun nouveau message");
define("_PHOTOS_DERNIERES", "Dernières photos");
define("_RECHERCHER", "Rechercher");
define("_RECRUTEMENT", "Recrutement");
define("_RSS_ACTU", "Les 20 dernières nouveautés");
define("_RSS_ARTICLES", "Les 20 derniers articles");
define("_RSS_TELECHARGEMENTS", "Les 20 derniers téléchargements");
define("_RSS_LIENS", "Les 20 derniers liens web");
define("_RSS_GALERIE", "Les 20 dernières images");
define("_RSS_FORUM", "Les 20 derniers sujets du forum");
define("_STATS", "Statistiques");
define("_SUGGESTIONS", "Suggestions");
define("_TELECHARGEMENTS", "Téléchargements");
define("_USER_CONNEXION", "Connexion");
define("_USER_CONNEXION_TITRE", "Connexion à un compte existant");
define("_USER_DECONNEXION", "Déconnexion");
define("_USER_DECONNEXION_TITRE", "Se déconnecter du site");
define("_USER_ENREGISTREMENT", "Enregistrement");
define("_USER_ENREGISTREMENT_TITRE", "Créer un compte");
define("_USER_COMPTE_TITLE", "Accéder à mon compte");
define("_USER_ADMIN", "Admin");
define("_USER_ADMIN_TITLE", "Administration du site");
define("_USER_PASSPERDU", "?");
define("_USER_PASSPERDU_TITRE", "Mot de passe oublié ?");
define("_USER_OK", "OK");
define("_VIDEO_MOMENT", "Vidéo du moment");
define("_REGISTEREDUSERS", "membre(s) inscrit");
define("_WEHAVE", "Il y a");
define("_LASTREGISTEREDUSER", "Dernier membre inscrit");
define("_MEMBERTOTALMESSAGES", "Il y a");
define("_MESSAGES2", "message(s) sur le forum");
?>